      ; camera section 

        CamX dq 0.0;0.0
        CamY dq 0.0
        CamZ dq 90.0

        WatchX dq 0.0
        WatchY dq 0.0 
        WatchZ dq -100.0 ; 0.0
        
        UpvecX dq 0.0
        UpvecY dq 1.0
        UpvecZ dq 0.0

        waveX dd 0.01
        waveStep dd 0.1
        waveSin dd ?

        
        one       db 1       ; java moment
        two       db 2
        three     db 3    
        twodd     dd 2.0    
 