
        ; main menu 
        buttStartX1     dd      25.0    
        buttStartY1     dd      26.0
        buttStartZ1     dd      0.0

        buttStartX2     dd      85.0
        buttStartY2     dd      43.0
        buttStartZ2     dd      0.0

        buttCardsX1     dd      25.0
        buttCardsY1     dd      3.0
        buttCardsZ1     dd      0.0

        buttCardsX2     dd      85.0
        buttCardsY2     dd      20.0
        buttCardsZ2     dd      0.0
        
        buttSettsX1     dd      25.0
        buttSettsY1     dd      -20.0
        buttSettsZ1     dd      0.0

        buttSettsX2     dd      85.0
        buttSettsY2     dd      -3.0
        buttSettsZ2     dd      0.0

        buttExitX1      dd      25.0
        buttExitY1      dd      -43.0
        buttExitZ1      dd      0.0

        buttExitX2      dd      85.0
        buttExitY2      dd      -26.0
        buttExitZ2      dd      0.0

        buttStartBrdr   dd      0
        buttCardsBrdr   dd      0
        buttSettsBrdr   dd      0  
        buttExitBrdr    dd      0

